# custom_client_executor.py
# AUTO-GENERATED by ResonTech Workspace Builder
# Class: GenericClientExecutor  (matches config_fed_client.json executor path)
#
# Sections between ── and ── mirror your config_fed_client.json hyperparams.
# Update them if you change the hyperparams in the UI.
import importlib
import os
import traceback
import numpy as np
import torch
from nvflare.apis.dxo import DXO, DataKind, MetaKey, from_shareable
from nvflare.apis.event_type import EventType
from nvflare.apis.executor import Executor
from nvflare.apis.fl_constant import FLMetaKey, ReturnCode
from nvflare.apis.fl_context import FLContext
from nvflare.apis.shareable import Shareable, make_reply
from nvflare.apis.signal import Signal
from nvflare.app_common.abstract.model import ModelLearnableKey
from nvflare.app_common.app_constant import AppConstants


class GenericClientExecutor(Executor):
    def __init__(
        self,
        data_root: str = "/var/tmp/nvflare/data",
        adapter_module: str = "model_def",
        train_fn: str = "fl_train_model",
        validate_fn: str = "fl_validate_model",
        # ── custom hyperparams ────────────────────────────────────────────────
        local_epochs: int = 2,
        batch_size: int = 32,
        learning_rate: float = 0.001,
        # ─────────────────────────────────────────────────────────────────────
        out_dir_name: str = "runs",
    ):
        super().__init__()
        self.data_root = data_root
        self.adapter_module = adapter_module
        self.train_fn = train_fn
        self.validate_fn = validate_fn
        # ── custom hyperparams ────────────────────────────────────────────────
        self.local_epochs = int(local_epochs)
        self.batch_size = int(batch_size)
        self.learning_rate = float(learning_rate)
        # ─────────────────────────────────────────────────────────────────────
        self.out_root = os.path.join(data_root, out_dir_name)
        self._device = None

    def handle_event(self, event_type: str, fl_ctx: FLContext):
        if event_type == EventType.START_RUN:
            self._device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            os.makedirs(self.out_root, exist_ok=True)

    def execute(self, task_name: str, shareable: Shareable, fl_ctx: FLContext, abort_signal: Signal) -> Shareable:
        try:
            if abort_signal.triggered:
                return make_reply(ReturnCode.TASK_ABORTED)
            if task_name == "train":
                return self._train(shareable, fl_ctx, abort_signal)
            elif task_name == "validate":
                return self._validate(shareable, fl_ctx, abort_signal)
            else:
                return make_reply(ReturnCode.TASK_UNKNOWN)
        except Exception:
            self.log_error(fl_ctx, traceback.format_exc())
            return make_reply(ReturnCode.EXECUTION_EXCEPTION)

    def _train(self, shareable: Shareable, fl_ctx: FLContext, abort_signal: Signal) -> Shareable:
        try:
            current_round = shareable.get_header(AppConstants.CURRENT_ROUND, 0)
            incoming_dxo = from_shareable(shareable)
            data = incoming_dxo.data
            global_weights = data.get(ModelLearnableKey.WEIGHTS, data) if isinstance(data, dict) else data
            if isinstance(global_weights, dict):
                global_weights = {k: torch.as_tensor(v) for k, v in global_weights.items()}

            adapter = importlib.import_module(self.adapter_module)
            train_fn = getattr(adapter, self.train_fn)

            def _adapter_log(ev):
                try:
                    msg = ev.get("msg", str(ev)) if isinstance(ev, dict) else str(ev)
                    self.log_info(fl_ctx, msg)
                except Exception:
                    pass

            payload = {
                "dataset": {
                    "data_root": "/app/payload",
                },
                "env": {
                    "SITE_NAME": fl_ctx.get_identity_name(),
                    "JOB_ID": fl_ctx.get_job_id(),
                    "CURRENT_ROUND": current_round,
                    "DEVICE": str(self._device),
                    # ── custom hyperparams ────────────────────────────────────
                    "local_epochs": self.local_epochs,
                    "batch_size": self.batch_size,
                    "learning_rate": self.learning_rate,
                    # ─────────────────────────────────────────────────────────
                },
                "initial_weights": global_weights,
            }

            output_dir = os.path.join(self.out_root, f"round_{current_round}")
            os.makedirs(output_dir, exist_ok=True)
            result = train_fn(payload, out_dir=output_dir, logger=_adapter_log)

            # Extract weights — prefer in-memory dict returned by adapter, fall back to file
            weights = None
            if isinstance(result, dict):
                if isinstance(result.get("weights"), dict):
                    weights = result["weights"]
                elif isinstance(result.get("state_dict"), dict):
                    weights = result["state_dict"]

            if weights is None:
                out_path = (result or {}).get("final_checkpoint") or os.path.join(output_dir, "state_dict.pt")
                if os.path.exists(out_path):
                    ckpt = torch.load(out_path, map_location="cpu")
                    weights = ckpt.get("model_state", ckpt) if isinstance(ckpt, dict) else ckpt

            if not isinstance(weights, dict) or len(weights) < 1:
                raise ValueError(f"No valid weights returned from training round {current_round}")

            weights_np = {
                k: v.cpu().numpy() if hasattr(v, "numpy") else np.array(v)
                for k, v in weights.items()
            }
            samples = result.get("samples", 0) if isinstance(result, dict) else 0
            dxo = DXO(
                data_kind=DataKind.WEIGHTS,
                data=weights_np,
                meta={
                    FLMetaKey.NUM_STEPS_CURRENT_ROUND: samples,
                    MetaKey.NUM_STEPS_CURRENT_ROUND: samples,
                },
            )
            return dxo.to_shareable()
        except Exception:
            self.log_error(fl_ctx, traceback.format_exc())
            return make_reply(ReturnCode.EXECUTION_EXCEPTION)

    def _validate(self, shareable: Shareable, fl_ctx: FLContext, abort_signal: Signal) -> Shareable:
        response = Shareable()
        response["status"] = "ok"
        return response
