# ─────────────────────────────────────────────────────────────────────────
# TEMPLATE — this is what `sdk.rt_submit_inference(..., inference=cfg)`
# (GENERATOR mode) writes as scripts/<entry>_serve.py before you fill in
# real inference logic.
#
# DO NOT load this file in production — it ALWAYS raises NotImplementedError
# from load_weights() and returns a sanity dict from predict().
# ─────────────────────────────────────────────────────────────────────────
"""Generated by ResonTech SDK.

The wrapper requires:
    __init__(**init_args)         once per replica
    predict(data: bytes) -> dict  per request (raw HTTP body in)

Optional hooks the wrapper calls when present (else sensible defaults):
    load_weights(path: str)       at startup, when inference.yaml sets
                                  model.path AND this method exists
    warmup()                      once after deploy — pre-warm caches
    health() -> dict              GET /health (default: {"status": "ok"})
"""
from __future__ import annotations

from typing import Any


class ModelPredictor:
    def __init__(
        self,
        num_classes: int = 3,
        chip_size: int = 512,
        overlay_alpha: float = 0.5,
        gn_groups: int = 32,
        class_names: list = ["background", "forest", "bushes"],
        palette: list = [[0, 0, 0], [0, 255, 120], [120, 0, 0]],
    ) -> None:
        self.num_classes = num_classes
        self.chip_size = chip_size
        self.overlay_alpha = overlay_alpha
        self.gn_groups = gn_groups
        self.class_names = class_names
        self.palette = palette
        # TODO: build your model + preprocessing here (runs once per replica).

    def load_weights(self, weights_path: str) -> None:
        # Wrapper invokes this with the absolute path to GLOBAL_MODEL_bs10_w3.pt
        # (mounted from "<runtime>/model/GLOBAL_MODEL_bs10_w3.pt") on every replica.
        #
        # Example (PyTorch):
        #   import torch
        #   state = torch.load(weights_path, map_location="cpu")
        #   self.model.load_state_dict(state, strict=False)
        raise NotImplementedError("Implement load_weights().")

    def predict(self, data: bytes) -> dict[str, Any]:
        # TODO: parse `data`, run inference, return a JSON-serializable dict.
        return {
            "model": "ModelPredictor",
            "received_bytes": len(data),
            "note": "Replace predict() with real inference logic.",
        }
